### ISSUE TITLE
Add type hinting and docstring to code

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#213]
Code within this repository often does not have docstrings or type hinting. Add docstrings and type hinting would help make the code more self-documenting and assist other developers in understanding the purpose and functionality of the code involved.

I can begin work on this. The process would not necessarily be an involved one -- I can happily pass scripts to ChatGPT, ask it to provide type hinting and comments without changing the underlying logic, and then manually inspect the results. I could then double check by running the tests provided to ensure the underlying logic is still functioning as expected.

**Comment by josh-chamberlain** [comment]
This is a good idea—docstrings help orient people and type hinting is important. I can also help as needed by giving context about broader goals, if there is a question about purpose. Don't want to miss the forest for the trees

**Comment by maxachis** [comment]
I've created my first of several pull requests, this one affecting the `middleware` directory. I intend to break up the pull requests by directory just to reduce the review burden for any single pull request.

**Comment by maxachis** [comment]
@josh-chamberlain It might be useful to look into adding:

- A linter for docstring such as [pydocstyle](https://www.pydocstyle.org/en/stable/)
- A static type checker such as [mypy](https://mypy-lang.org/)

These would be similar to the black linter we already have in place.

Code would look something like this:

```yaml
name: Python Style and Type Check

on: [push, pull_request]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy pydocstyle
    - name: Check docstrings
      run: pydocstyle <your_package_or_module>
    - name: Check type hints
      run: mypy <your_package_or_module>
```

Let me know if you think this is an angle worth pursuing.
