### ISSUE TITLE
Set up containerized version of app

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#568]
### Context

While running development, we run into some issues because often our hardware and setup does not perfectly mirror the setup we'll see when we deploy the app on Digital Ocean. The way to resolve that is to create a containerized version of the app, probably using Docker containers, which can provide a single source of truth for the operation of the app.

### Requirements

- [x] Determine how to properly set up a docker container for the web app
- [x] Determine how to properly link up the docker container so that it deploys as expected on Digital Ocean.
- [x] Then implement both
- [ ] Ensure runtime logs still print from container in Digital Ocean.

### Tests

* Anything we should test for? How should it be tested?

### Docs

* What docs should be updated? Link to related docs changes in the PR.

### Open questions

* Any uncertainties? Anything we're flexible about?

**Comment by maxachis** [comment]
# Resources

* [How To Dockerize A Flask App](https://www.freecodecamp.org/news/how-to-dockerize-a-flask-app/)

**Comment by josh-chamberlain** [comment]
>> Should we update the GitHub action to somehow start up the docker container and then run the tests through that? Or is the fact that it's already in a GitHub action be sufficient containerization?
>
> Good question. My initial impulse is to use the dockerfile everywhere, just for consistency's sake. But I don't know how that works in the context of automation runners.

Using the docker container for tests makes intuitive sense to me—to replicate the environment. I'm not sure how much it _really_ matters.

**Comment by maxachis** [comment]
A container for the API has been set up in the repository and integrated into data-sources-v2-dev, per the work done in #584

**Comment by maxachis** [comment]
One unexpected component of containerization is that we don't have direct access to the runtime logs generated within the container now. So we can't see logs of requests being made, which would put us at a disadvantage when it comes to diagnosing a problem.

We'll want to figure out how to solve for that problem.

**Comment by josh-chamberlain** [comment]
@maxachis am I correct in interpreting this as the same as the log forwarding we set up in Digital Ocean? I'm sure other folks are sending logs to papertrail with our exact setup. https://www.papertrail.com/help/configuring-centralized-logging-from-docker/

**Comment by maxachis** [comment]
Removed the `dev` digital ocean container setup until I've got the logging thing figured out. But for future reference, here's the relevant snippet of the yaml file:

```yaml
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: Police-Data-Accessibility-Project/data-sources-app-v2
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: v2-app
  run_command: gunicorn --worker-tmp-dir /dev/shm 'app:create_app()'
  source_dir: /

```

**Comment by maxachis** [comment]
Finally fixed this in dev! We need to merge the latest changes into `main`, and then after that, we'll need to make this change to the `main` yaml file:

```yaml
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: Police-Data-Accessibility-Project/data-sources-app
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: data-sources-app
  run_command: gunicorn --worker-tmp-dir /dev/shm --access-logfile - --error-logfile
    - 'app:create_app()'
  source_dir: /
```
